### ISSUE TITLE
/home/mafutragil/www/GroupHelp/api/rolesManager.js:458     if(!chat.users.hasOwnProperty(userId))

### ISSUE THREAD

**Issue by GeekSupport** [Sp3rick/GroupHelp#32]
TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')    at Object.sumUserPerms (/home/mafutragil/www/GroupHelp/api/rolesManager.js:458:20)
    at TelegramBot.<anonymous> (/home/mafutragil/www/GroupHelp/main.js:100:27)
    at TelegramBot.emit (/home/mafutragil/www/GroupHelp/node_modules/eventemitter3/index.js:182:35)
    at TelegramBot.processUpdate (/home/mafutragil/www/GroupHelp/node_modules/node-telegram-bot-api/src/telegram.js:702:12)
    at /home/mafutragil/www/GroupHelp/node_modules/node-telegram-bot-api/src/telegramPolling.js:110:22
    at Array.forEach (<anonymous>)
    at /home/mafutragil/www/GroupHelp/node_modules/node-telegram-bot-api/src/telegramPolling.js:106:17
    at tryCatcher (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/home/mafutragil/www/GroupHelp/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
Node.js v18.19.1

**Comment by Sp3rick** [comment]
Are you sure nodejs has write permissions? check /home/mafutragil/www/GroupHelp/database/chats/-chatId.json
if the file exhist send it here

I also made a commit a little while ago (0.1.19), check it also if there is the problem in the latter

**Comment by GeekSupport** [comment]
There is no such file

**Comment by Sp3rick** [comment]
the bot need write permissions to work, try run it in some other folder like /home/mafutragil/GroupHelp, if it's ok it will create a ./database folder

**Comment by GeekSupport** [comment]
Still the same
     if(!chat.users.hasOwnProperty(userId))
                   ^
TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')    at Object.sumUserPerms (/home/mafutragil/www/GroupHelp/api/rolesManager.js:458:20)
    at TelegramBot.<anonymous> (/home/mafutragil/www/GroupHelp/main.js:100:27)

**Comment by Sp3rick** [comment]
should be fixed on last push

**Comment by GeekSupport** [comment]
/home/mafutragil/www/GroupHelp/plugins/menu.js:83
            GHbot.sendMessage(user.id, user.id, l[user.lang].PRESENTATION.replace("{name}",user.first_name+" "+(user.last_name||"")),{
                                                             ^
TypeError: Cannot read properties of undefined (reading 'PRESENTATION')
    at EventEmitter.<anonymous> (/home/mafutragil/www/GroupHelp/plugins/menu.js:83:62)
    at EventEmitter.emit (node:events:525:35)
    at TelegramBot.<anonymous> (/home/mafutragil/www/GroupHelp/main.js:147:22)

**Comment by Sp3rick** [comment]
can you tell me  the steps to reproduce this error?
